name: Daily Meta Ads Sync

on:
  schedule:
    - cron: '0 10 * * *'  # every day at 10:00 UTC (adjust for your timezone)
  workflow_dispatch:      # lets you run it manually too

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Meta Ads script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python3 meta_ads_monitoring.py
